// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DefaultConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=SalaryAccountManagementPortal;Integrated Security=True`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace App.DataModels.Models
{
    /// <summary>
    /// A class which represents the app_activity table.
    /// </summary>
	[Table("app_activity")]
	public partial class appactivity
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string audit_username { get; set; }
		public virtual string audit_fullname { get; set; }
		public virtual string audit_ipaddress { get; set; }
		public virtual string audit_macaddress { get; set; }
		public virtual string operation { get; set; }
		public virtual string comments { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
	}

    /// <summary>
    /// A class which represents the email_log table.
    /// </summary>
	[Table("email_log")]
	public partial class emaillog
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string subject { get; set; }
		public virtual string message { get; set; }
		public virtual bool is_message_html_body { get; set; }
		public virtual string recipients { get; set; }
		public virtual string copy { get; set; }
		public virtual string blind_copy { get; set; }
		public virtual DateTime logged_on { get; set; }
		public virtual string logged_by { get; set; }
		public virtual long? send_attempts { get; set; }
		public virtual DateTime? last_modified_on { get; set; }
		public virtual string last_modified_by { get; set; }
		public virtual bool sent_flag { get; set; }
		public virtual DateTime? sent_on { get; set; }
		public virtual string sent_by { get; set; }
	}

    /// <summary>
    /// A class which represents the fintech table.
    /// </summary>
	[Table("fintech")]
	public partial class fintech
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string corporate_name { get; set; }
		public virtual string official_email_address { get; set; }
		public virtual string head_office_address { get; set; }
		public virtual string relationship_manager_staff_id { get; set; }
		public virtual long relationship_manager_person_id { get; set; }
		public virtual string relationship_manager_sol_id { get; set; }
		public virtual string relationship_manager_sol_name { get; set; }
		public virtual string relationship_manager_sol_address { get; set; }
		public virtual string account_number { get; set; }
		public virtual string account_name { get; set; }
		public virtual string finacle_term_id { get; set; }
		public virtual string fee_scale { get; set; }
		public virtual decimal scale_value { get; set; }
		public virtual decimal cap_amount { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual DateTime? approved_on { get; set; }
		public virtual string approved_by { get; set; }
		public virtual DateTime? last_modified_on { get; set; }
		public virtual string last_modified_by { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual person person { get; set; }
		public virtual IEnumerable<fintechcontactperson> fintechcontactpersons { get; set; }
		public virtual IEnumerable<fintechfeeoperationlog> fintechfeeoperationlog { get; set; }
		public virtual IEnumerable<fintechonboardingdocument> fintechonboardingdocuments { get; set; }
	}

    /// <summary>
    /// A class which represents the salary_payment_history table.
    /// </summary>
	[Table("salary_payment_history")]
	public partial class salarypaymenthistory
	{
		[Key]
		public virtual long id { get; set; }
		public virtual long salary_accounts_rac_profiling_id { get; set; }
		public virtual string month { get; set; }
		public virtual decimal amount { get; set; }
		public virtual DateTime? transaction_date { get; set; }
		public virtual string evidence_save_path { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual DateTime? approved_on { get; set; }
		public virtual string approved_by { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual salaryaccountsracprofiling salaryaccountsracprofiling { get; set; }
	}

    /// <summary>
    /// A class which represents the fintech_contact_persons table.
    /// </summary>
	[Table("fintech_contact_persons")]
	public partial class fintechcontactperson
	{
		[Key]
		public virtual long id { get; set; }
		public virtual long fintech_id { get; set; }
		public virtual long person_id { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual fintech fintech { get; set; }
		public virtual person person { get; set; }
	}

    /// <summary>
    /// A class which represents the fintech_fee_operation_log table.
    /// </summary>
	[Table("fintech_fee_operation_log")]
	public partial class fintechfeeoperationlog
	{
		[Key]
		public virtual long id { get; set; }
		public virtual long fintech_id { get; set; }
		public virtual int operation_id { get; set; }
		public virtual string operation_data { get; set; }
		public virtual DateTime initiated_on { get; set; }
		public virtual string initiated_by { get; set; }
		public virtual int operation_status_id { get; set; }
		public virtual DateTime? operated_on { get; set; }
		public virtual string operated_by { get; set; }
		public virtual fintech fintech { get; set; }
	}

    /// <summary>
    /// A class which represents the fintech_onboarding_documents table.
    /// </summary>
	[Table("fintech_onboarding_documents")]
	public partial class fintechonboardingdocument
	{
		[Key]
		public virtual long id { get; set; }
		public virtual long fintech_id { get; set; }
		public virtual long document_id { get; set; }
		public virtual string document_save_path { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual DateTime? approved_on { get; set; }
		public virtual string approved_by { get; set; }
		public virtual DateTime? last_modified_on { get; set; }
		public virtual string last_modified_by { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual fintech fintech { get; set; }
		public virtual onboardingdocument onboardingdocument { get; set; }
	}

    /// <summary>
    /// A class which represents the forgot_password_log table.
    /// </summary>
	[Table("forgot_password_log")]
	public partial class forgotpasswordlog
	{
		[Key]
		public virtual long id { get; set; }
		public virtual long person_id { get; set; }
		public virtual string username { get; set; }
		public virtual string forgot_password_code { get; set; }
		public virtual DateTime forgot_password_generated_date { get; set; }
		public virtual person person { get; set; }
	}

    /// <summary>
    /// A class which represents the main_menu table.
    /// </summary>
	[Table("main_menu")]
	public partial class mainmenu
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string display_name { get; set; }
		public virtual long menu_icon_id { get; set; }
		public virtual bool active_flag { get; set; }
		public virtual int arrangement_order { get; set; }
		public virtual menuicon menuicon { get; set; }
		public virtual IEnumerable<submenu> submenu { get; set; }
	}

    /// <summary>
    /// A class which represents the users table.
    /// </summary>
	[Table("users")]
	public partial class user
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string username { get; set; }
		public virtual int authentication_type_id { get; set; }
		public virtual bool branch_user_flag { get; set; }
		public virtual string local_password { get; set; }
		public virtual DateTime? password_expiry_date { get; set; }
		public virtual long person_id { get; set; }
		public virtual long role_id { get; set; }
		public virtual int? security_question_id { get; set; }
		public virtual string security_question_answer { get; set; }
		public virtual int status_id { get; set; }
		public virtual DateTime? last_login_date { get; set; }
		public virtual DateTime? last_logout_date { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual DateTime? approved_on { get; set; }
		public virtual string approved_by { get; set; }
		public virtual DateTime? last_modified_on { get; set; }
		public virtual string last_modified_by { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual useraccountauthenticationtype useraccountauthenticationtype { get; set; }
		public virtual person person { get; set; }
		public virtual role role { get; set; }
		public virtual securityquestion securityquestion { get; set; }
		public virtual useraccountstatu useraccountstatu { get; set; }
	}

    /// <summary>
    /// A class which represents the menu_icon table.
    /// </summary>
	[Table("menu_icon")]
	public partial class menuicon
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string name { get; set; }
		public virtual bool active_flag { get; set; }
		public virtual IEnumerable<mainmenu> mainmenu { get; set; }
	}

    /// <summary>
    /// A class which represents the onboarding_documents table.
    /// </summary>
	[Table("onboarding_documents")]
	public partial class onboardingdocument
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string document_name { get; set; }
		public virtual bool mandatory_flag { get; set; }
		public virtual bool active_flag { get; set; }
		public virtual IEnumerable<fintechonboardingdocument> fintechonboardingdocuments { get; set; }
	}

    /// <summary>
    /// A class which represents the password_change_log table.
    /// </summary>
	[Table("password_change_log")]
	public partial class passwordchangelog
	{
		[Key]
		public virtual long id { get; set; }
		public virtual long person_id { get; set; }
		public virtual string username { get; set; }
		public virtual string password { get; set; }
		public virtual DateTime logged_on { get; set; }
		public virtual person person { get; set; }
	}

    /// <summary>
    /// A class which represents the person table.
    /// </summary>
	[Table("person")]
	public partial class person
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string surname { get; set; }
		public virtual string first_name { get; set; }
		public virtual string middle_name { get; set; }
		public virtual string mobile_number { get; set; }
		public virtual string email_address { get; set; }
		public virtual string passport { get; set; }
		public virtual string signature { get; set; }
		public virtual int person_type_id { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual DateTime? last_modified_on { get; set; }
		public virtual string last_modified_by { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual persontype persontype { get; set; }
		public virtual IEnumerable<user> users { get; set; }
		public virtual IEnumerable<fintech> fintech { get; set; }
		public virtual IEnumerable<fintechcontactperson> fintechcontactpersons { get; set; }
		public virtual IEnumerable<forgotpasswordlog> forgotpasswordlog { get; set; }
		public virtual IEnumerable<passwordchangelog> passwordchangelog { get; set; }
	}

    /// <summary>
    /// A class which represents the person_type table.
    /// </summary>
	[Table("person_type")]
	public partial class persontype
	{
		[Key]
		public virtual int id { get; set; }
		public virtual string person_type_name { get; set; }
		public virtual IEnumerable<person> person { get; set; }
	}

    /// <summary>
    /// A class which represents the role_menu table.
    /// </summary>
	[Table("role_menu")]
	public partial class rolemenu
	{
		[Key]
		public virtual long id { get; set; }
		public virtual long role_id { get; set; }
		public virtual long menu_sub_id { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual role role { get; set; }
		public virtual submenu submenu { get; set; }
	}

    /// <summary>
    /// A class which represents the maker_checker_log table.
    /// </summary>
	[Table("maker_checker_log")]
	public partial class makercheckerlog
	{
		[Key]
		public virtual long id { get; set; }
		public virtual int maker_checker_category_id { get; set; }
		public virtual int maker_checker_type_id { get; set; }
		public virtual string action_name { get; set; }
		public virtual string action_details { get; set; }
		public virtual string action_data { get; set; }
		public virtual long maker_person_id { get; set; }
		public virtual string maker_username { get; set; }
		public virtual string maker_fullname { get; set; }
		public virtual string maker_sol_id { get; set; }
		public virtual string maker_sol_name { get; set; }
		public virtual string maker_sol_address { get; set; }
		public virtual int maker_checker_status { get; set; }
		public virtual DateTime date_made { get; set; }
		public virtual long? checker_person_id { get; set; }
		public virtual string checker_username { get; set; }
		public virtual string checker_fullname { get; set; }
		public virtual string checker_sol_id { get; set; }
		public virtual string checker_sol_name { get; set; }
		public virtual string checker_sol_address { get; set; }
		public virtual string checker_remarks { get; set; }
		public virtual DateTime? date_checked { get; set; }
		public virtual Guid query_string { get; set; }
	}

    /// <summary>
    /// A class which represents the roles table.
    /// </summary>
	[Table("roles")]
	public partial class role
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string role_name { get; set; }
		public virtual bool active_flag { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual DateTime? approved_on { get; set; }
		public virtual string approved_by { get; set; }
		public virtual DateTime? last_modified_on { get; set; }
		public virtual string last_modified_by { get; set; }
		public virtual bool system_reserved_flag { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual IEnumerable<user> users { get; set; }
		public virtual IEnumerable<rolemenu> rolemenu { get; set; }
	}

    /// <summary>
    /// A class which represents the security_question table.
    /// </summary>
	[Table("security_question")]
	public partial class securityquestion
	{
		[Key]
		public virtual int id { get; set; }
		public virtual string question { get; set; }
		public virtual bool active_flag { get; set; }
		public virtual IEnumerable<user> users { get; set; }
	}

    /// <summary>
    /// A class which represents the sub_menu table.
    /// </summary>
	[Table("sub_menu")]
	public partial class submenu
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string display_name { get; set; }
		public virtual string access_name { get; set; }
		public virtual long main_menu_id { get; set; }
		public virtual string url { get; set; }
		public virtual bool active_flag { get; set; }
		public virtual int arrangement_order { get; set; }
		public virtual bool display_flag { get; set; }
		public virtual bool maker_page_flag { get; set; }
		public virtual long? checker_page_id { get; set; }
		public virtual mainmenu mainmenu { get; set; }
		public virtual IEnumerable<rolemenu> rolemenu { get; set; }
	}

    /// <summary>
    /// A class which represents the Transactions table.
    /// </summary>
	[Table("Transactions")]
	public partial class Transaction
	{
		public virtual long id { get; set; }
		public virtual string HashedPan { get; set; }
		public virtual string TruncatedPan { get; set; }
		public virtual string AppName { get; set; }
		public virtual decimal? Amount { get; set; }
		public virtual DateTime? ValueDate { get; set; }
		public virtual string STAN { get; set; }
		public virtual string FintechName { get; set; }
		public virtual string MerchantID { get; set; }
		public virtual string Narration { get; set; }
		public virtual string RRN { get; set; }
		public virtual string ResponseCode { get; set; }
		public virtual string ResponseMessage { get; set; }
		public virtual string SourceIPAddress { get; set; }
		public virtual DateTime? RequestTime { get; set; }
		public virtual DateTime? FEPResponseTime { get; set; }
	}

    /// <summary>
    /// A class which represents the salary_accounts_rac_profiling table.
    /// </summary>
	[Table("salary_accounts_rac_profiling")]
	public partial class salaryaccountsracprofiling
	{
		[Key]
		public virtual long id { get; set; }
		public virtual long salary_account_id { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual DateTime? approved_on { get; set; }
		public virtual string approved_by { get; set; }
		public virtual int? rac_profiled_status_id { get; set; }
		public virtual DateTime? rac_profiled_on { get; set; }
		public virtual string rac_profiled_by { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual salaryaccount salaryaccount { get; set; }
		public virtual IEnumerable<salarypaymenthistory> salarypaymenthistory { get; set; }
	}

    /// <summary>
    /// A class which represents the user_access_activity table.
    /// </summary>
	[Table("user_access_activity")]
	public partial class useraccessactivity
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string username { get; set; }
		public virtual string fullname { get; set; }
		public virtual string ipaddress { get; set; }
		public virtual string macaddress { get; set; }
		public virtual string access_key { get; set; }
		public virtual DateTime? key_expiration_date { get; set; }
		public virtual string remarks { get; set; }
		public virtual bool? ignore_for_account_lock { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual DateTime? logout_date { get; set; }
	}

    /// <summary>
    /// A class which represents the user_account_authentication_type table.
    /// </summary>
	[Table("user_account_authentication_type")]
	public partial class useraccountauthenticationtype
	{
		[Key]
		public virtual int id { get; set; }
		public virtual string authentication_type_name { get; set; }
		public virtual bool active_flag { get; set; }
		public virtual IEnumerable<user> users { get; set; }
	}

    /// <summary>
    /// A class which represents the user_account_status table.
    /// </summary>
	[Table("user_account_status")]
	public partial class useraccountstatu
	{
		[Key]
		public virtual int id { get; set; }
		public virtual string account_status { get; set; }
		public virtual IEnumerable<user> users { get; set; }
	}

    /// <summary>
    /// A class which represents the employer table.
    /// </summary>
	[Table("employer")]
	public partial class employer
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string employer_name { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual DateTime? approved_on { get; set; }
		public virtual string approved_by { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual IEnumerable<salaryaccountsemployer> salaryaccountsemployers { get; set; }
	}

    /// <summary>
    /// A class which represents the salary_accounts_employers table.
    /// </summary>
	[Table("salary_accounts_employers")]
	public partial class salaryaccountsemployer
	{
		[Key]
		public virtual long id { get; set; }
		public virtual long salary_account_id { get; set; }
		public virtual long employer_id { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual DateTime? approved_on { get; set; }
		public virtual string approved_by { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual salaryaccount salaryaccount { get; set; }
		public virtual employer employer { get; set; }
	}

    /// <summary>
    /// A class which represents the salary_accounts table.
    /// </summary>
	[Table("salary_accounts")]
	public partial class salaryaccount
	{
		[Key]
		public virtual long id { get; set; }
		public virtual string account_number { get; set; }
		public virtual string account_name { get; set; }
		public virtual DateTime created_on { get; set; }
		public virtual string created_by { get; set; }
		public virtual DateTime? approved_on { get; set; }
		public virtual string approved_by { get; set; }
		public virtual Guid query_string { get; set; }
		public virtual IEnumerable<salaryaccountsracprofiling> salaryaccountsracprofiling { get; set; }
		public virtual IEnumerable<salaryaccountsemployer> salaryaccountsemployers { get; set; }
	}

}
