//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.249.199/FBNServices/service.asmx")]
        public string App_Core_AdServiceClient_Service {
            get {
                return ((string)(this["App_Core_AdServiceClient_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.249.199/EntrustWrapper/AuthWrapper.svc")]
        public string App_Core_EntrustServiceClient_AuthWrapper {
            get {
                return ((string)(this["App_Core_EntrustServiceClient_AuthWrapper"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://online.firstcentralcreditbureau.com/firstcentralnigeriawebservice/FirstCe" +
            "ntralNigeriaWebService.asmx")]
        public string App_Core_CreditBureauServiceClient_FirstCentralNigeriaWebService {
            get {
                return ((string)(this["App_Core_CreditBureauServiceClient_FirstCentralNigeriaWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nibbs-bvn-validator-dev.fbn-devops-dev-asenv.appserviceenvironment.net/Ser" +
            "vice.svc")]
        public string App_Core_BvnValidatorServiceClient_Service {
            get {
                return ((string)(this["App_Core_BvnValidatorServiceClient_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.163.20.65:7101/CRMS-Core-Model-webapp/ReturnSubmissionWSEJBBeanService")]
        public string App_Core_CRMSServiceClient_ReturnSubmissionWSEJBBeanService {
            get {
                return ((string)(this["App_Core_CRMSServiceClient_ReturnSubmissionWSEJBBeanService"]));
            }
        }
    }
}
