//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace App.Core.BvnValidatorServiceClient {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService", Namespace="http://tempuri.org/")]
    public partial class BasicHttpBinding_IService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BVNEnquiryOperationCompleted;
        
        private System.Threading.SendOrPostCallback BVNEnquiry2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateBVNOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateBVNWithAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkBVNWithAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkBVNWithAccountiBPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkBVNWithCustIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutoLinkBVNWithAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateBVNOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BasicHttpBinding_IService() {
            this.Url = global::App.Core.Properties.Settings.Default.App_Core_BvnValidatorServiceClient_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BVNEnquiryCompletedEventHandler BVNEnquiryCompleted;
        
        /// <remarks/>
        public event BVNEnquiry2CompletedEventHandler BVNEnquiry2Completed;
        
        /// <remarks/>
        public event ValidateBVNCompletedEventHandler ValidateBVNCompleted;
        
        /// <remarks/>
        public event ValidateBVNWithAccountCompletedEventHandler ValidateBVNWithAccountCompleted;
        
        /// <remarks/>
        public event LinkBVNWithAccountCompletedEventHandler LinkBVNWithAccountCompleted;
        
        /// <remarks/>
        public event LinkBVNWithAccountiBPSCompletedEventHandler LinkBVNWithAccountiBPSCompleted;
        
        /// <remarks/>
        public event LinkBVNWithCustIDCompletedEventHandler LinkBVNWithCustIDCompleted;
        
        /// <remarks/>
        public event AutoLinkBVNWithAccountCompletedEventHandler AutoLinkBVNWithAccountCompleted;
        
        /// <remarks/>
        public event UpdateBVNCompletedEventHandler UpdateBVNCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/BVNEnquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BVNEnquiryResponse BVNEnquiry([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string AccountNumber) {
            object[] results = this.Invoke("BVNEnquiry", new object[] {
                        AccountNumber});
            return ((BVNEnquiryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BVNEnquiryAsync(string AccountNumber) {
            this.BVNEnquiryAsync(AccountNumber, null);
        }
        
        /// <remarks/>
        public void BVNEnquiryAsync(string AccountNumber, object userState) {
            if ((this.BVNEnquiryOperationCompleted == null)) {
                this.BVNEnquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBVNEnquiryOperationCompleted);
            }
            this.InvokeAsync("BVNEnquiry", new object[] {
                        AccountNumber}, this.BVNEnquiryOperationCompleted, userState);
        }
        
        private void OnBVNEnquiryOperationCompleted(object arg) {
            if ((this.BVNEnquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BVNEnquiryCompleted(this, new BVNEnquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/BVNEnquiry2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BVNEnquiryResponse2 BVNEnquiry2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string AccountNumber) {
            object[] results = this.Invoke("BVNEnquiry2", new object[] {
                        AccountNumber});
            return ((BVNEnquiryResponse2)(results[0]));
        }
        
        /// <remarks/>
        public void BVNEnquiry2Async(string AccountNumber) {
            this.BVNEnquiry2Async(AccountNumber, null);
        }
        
        /// <remarks/>
        public void BVNEnquiry2Async(string AccountNumber, object userState) {
            if ((this.BVNEnquiry2OperationCompleted == null)) {
                this.BVNEnquiry2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnBVNEnquiry2OperationCompleted);
            }
            this.InvokeAsync("BVNEnquiry2", new object[] {
                        AccountNumber}, this.BVNEnquiry2OperationCompleted, userState);
        }
        
        private void OnBVNEnquiry2OperationCompleted(object arg) {
            if ((this.BVNEnquiry2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BVNEnquiry2Completed(this, new BVNEnquiry2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/ValidateBVN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ValidatorResponse ValidateBVN([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string BvnNumber) {
            object[] results = this.Invoke("ValidateBVN", new object[] {
                        BvnNumber});
            return ((ValidatorResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateBVNAsync(string BvnNumber) {
            this.ValidateBVNAsync(BvnNumber, null);
        }
        
        /// <remarks/>
        public void ValidateBVNAsync(string BvnNumber, object userState) {
            if ((this.ValidateBVNOperationCompleted == null)) {
                this.ValidateBVNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateBVNOperationCompleted);
            }
            this.InvokeAsync("ValidateBVN", new object[] {
                        BvnNumber}, this.ValidateBVNOperationCompleted, userState);
        }
        
        private void OnValidateBVNOperationCompleted(object arg) {
            if ((this.ValidateBVNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateBVNCompleted(this, new ValidateBVNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/ValidateBVNWithAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ValidatorResponse ValidateBVNWithAccount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string AccountNumber) {
            object[] results = this.Invoke("ValidateBVNWithAccount", new object[] {
                        AccountNumber});
            return ((ValidatorResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateBVNWithAccountAsync(string AccountNumber) {
            this.ValidateBVNWithAccountAsync(AccountNumber, null);
        }
        
        /// <remarks/>
        public void ValidateBVNWithAccountAsync(string AccountNumber, object userState) {
            if ((this.ValidateBVNWithAccountOperationCompleted == null)) {
                this.ValidateBVNWithAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateBVNWithAccountOperationCompleted);
            }
            this.InvokeAsync("ValidateBVNWithAccount", new object[] {
                        AccountNumber}, this.ValidateBVNWithAccountOperationCompleted, userState);
        }
        
        private void OnValidateBVNWithAccountOperationCompleted(object arg) {
            if ((this.ValidateBVNWithAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateBVNWithAccountCompleted(this, new ValidateBVNWithAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/LinkBVNWithAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LinkBVNResponse LinkBVNWithAccount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] LinkRequest Details) {
            object[] results = this.Invoke("LinkBVNWithAccount", new object[] {
                        Details});
            return ((LinkBVNResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LinkBVNWithAccountAsync(LinkRequest Details) {
            this.LinkBVNWithAccountAsync(Details, null);
        }
        
        /// <remarks/>
        public void LinkBVNWithAccountAsync(LinkRequest Details, object userState) {
            if ((this.LinkBVNWithAccountOperationCompleted == null)) {
                this.LinkBVNWithAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkBVNWithAccountOperationCompleted);
            }
            this.InvokeAsync("LinkBVNWithAccount", new object[] {
                        Details}, this.LinkBVNWithAccountOperationCompleted, userState);
        }
        
        private void OnLinkBVNWithAccountOperationCompleted(object arg) {
            if ((this.LinkBVNWithAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkBVNWithAccountCompleted(this, new LinkBVNWithAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/LinkBVNWithAccountiBPS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LinkBVNResponse LinkBVNWithAccountiBPS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] LinkRequestiBPS Details) {
            object[] results = this.Invoke("LinkBVNWithAccountiBPS", new object[] {
                        Details});
            return ((LinkBVNResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LinkBVNWithAccountiBPSAsync(LinkRequestiBPS Details) {
            this.LinkBVNWithAccountiBPSAsync(Details, null);
        }
        
        /// <remarks/>
        public void LinkBVNWithAccountiBPSAsync(LinkRequestiBPS Details, object userState) {
            if ((this.LinkBVNWithAccountiBPSOperationCompleted == null)) {
                this.LinkBVNWithAccountiBPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkBVNWithAccountiBPSOperationCompleted);
            }
            this.InvokeAsync("LinkBVNWithAccountiBPS", new object[] {
                        Details}, this.LinkBVNWithAccountiBPSOperationCompleted, userState);
        }
        
        private void OnLinkBVNWithAccountiBPSOperationCompleted(object arg) {
            if ((this.LinkBVNWithAccountiBPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkBVNWithAccountiBPSCompleted(this, new LinkBVNWithAccountiBPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/LinkBVNWithCustID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
        public LinkBVNResponse[] LinkBVNWithCustID([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] LinkRequestCustID Details) {
            object[] results = this.Invoke("LinkBVNWithCustID", new object[] {
                        Details});
            return ((LinkBVNResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void LinkBVNWithCustIDAsync(LinkRequestCustID Details) {
            this.LinkBVNWithCustIDAsync(Details, null);
        }
        
        /// <remarks/>
        public void LinkBVNWithCustIDAsync(LinkRequestCustID Details, object userState) {
            if ((this.LinkBVNWithCustIDOperationCompleted == null)) {
                this.LinkBVNWithCustIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkBVNWithCustIDOperationCompleted);
            }
            this.InvokeAsync("LinkBVNWithCustID", new object[] {
                        Details}, this.LinkBVNWithCustIDOperationCompleted, userState);
        }
        
        private void OnLinkBVNWithCustIDOperationCompleted(object arg) {
            if ((this.LinkBVNWithCustIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkBVNWithCustIDCompleted(this, new LinkBVNWithCustIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/AutoLinkBVNWithAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LinkBVNResponse AutoLinkBVNWithAccount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AutoLinkRequest Details) {
            object[] results = this.Invoke("AutoLinkBVNWithAccount", new object[] {
                        Details});
            return ((LinkBVNResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AutoLinkBVNWithAccountAsync(AutoLinkRequest Details) {
            this.AutoLinkBVNWithAccountAsync(Details, null);
        }
        
        /// <remarks/>
        public void AutoLinkBVNWithAccountAsync(AutoLinkRequest Details, object userState) {
            if ((this.AutoLinkBVNWithAccountOperationCompleted == null)) {
                this.AutoLinkBVNWithAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutoLinkBVNWithAccountOperationCompleted);
            }
            this.InvokeAsync("AutoLinkBVNWithAccount", new object[] {
                        Details}, this.AutoLinkBVNWithAccountOperationCompleted, userState);
        }
        
        private void OnAutoLinkBVNWithAccountOperationCompleted(object arg) {
            if ((this.AutoLinkBVNWithAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutoLinkBVNWithAccountCompleted(this, new AutoLinkBVNWithAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/UpdateBVN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UpdateBVNResponse UpdateBVN([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UpdateRequest Details) {
            object[] results = this.Invoke("UpdateBVN", new object[] {
                        Details});
            return ((UpdateBVNResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateBVNAsync(UpdateRequest Details) {
            this.UpdateBVNAsync(Details, null);
        }
        
        /// <remarks/>
        public void UpdateBVNAsync(UpdateRequest Details, object userState) {
            if ((this.UpdateBVNOperationCompleted == null)) {
                this.UpdateBVNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBVNOperationCompleted);
            }
            this.InvokeAsync("UpdateBVN", new object[] {
                        Details}, this.UpdateBVNOperationCompleted, userState);
        }
        
        private void OnUpdateBVNOperationCompleted(object arg) {
            if ((this.UpdateBVNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBVNCompleted(this, new UpdateBVNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpsBinding_IService", Namespace="http://tempuri.org/")]
    public partial class BasicHttpsBinding_IService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BVNEnquiryOperationCompleted;
        
        private System.Threading.SendOrPostCallback BVNEnquiry2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateBVNOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateBVNWithAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkBVNWithAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkBVNWithAccountiBPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkBVNWithCustIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutoLinkBVNWithAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateBVNOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BasicHttpsBinding_IService() {
            this.Url = "https://nibbs-bvn-validator-dev.fbn-devops-dev-asenv.appserviceenvironment.net/Se" +
                "rvice.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BVNEnquiryCompletedEventHandler BVNEnquiryCompleted;
        
        /// <remarks/>
        public event BVNEnquiry2CompletedEventHandler BVNEnquiry2Completed;
        
        /// <remarks/>
        public event ValidateBVNCompletedEventHandler ValidateBVNCompleted;
        
        /// <remarks/>
        public event ValidateBVNWithAccountCompletedEventHandler ValidateBVNWithAccountCompleted;
        
        /// <remarks/>
        public event LinkBVNWithAccountCompletedEventHandler LinkBVNWithAccountCompleted;
        
        /// <remarks/>
        public event LinkBVNWithAccountiBPSCompletedEventHandler LinkBVNWithAccountiBPSCompleted;
        
        /// <remarks/>
        public event LinkBVNWithCustIDCompletedEventHandler LinkBVNWithCustIDCompleted;
        
        /// <remarks/>
        public event AutoLinkBVNWithAccountCompletedEventHandler AutoLinkBVNWithAccountCompleted;
        
        /// <remarks/>
        public event UpdateBVNCompletedEventHandler UpdateBVNCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/BVNEnquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BVNEnquiryResponse BVNEnquiry([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string AccountNumber) {
            object[] results = this.Invoke("BVNEnquiry", new object[] {
                        AccountNumber});
            return ((BVNEnquiryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BVNEnquiryAsync(string AccountNumber) {
            this.BVNEnquiryAsync(AccountNumber, null);
        }
        
        /// <remarks/>
        public void BVNEnquiryAsync(string AccountNumber, object userState) {
            if ((this.BVNEnquiryOperationCompleted == null)) {
                this.BVNEnquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBVNEnquiryOperationCompleted);
            }
            this.InvokeAsync("BVNEnquiry", new object[] {
                        AccountNumber}, this.BVNEnquiryOperationCompleted, userState);
        }
        
        private void OnBVNEnquiryOperationCompleted(object arg) {
            if ((this.BVNEnquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BVNEnquiryCompleted(this, new BVNEnquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/BVNEnquiry2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BVNEnquiryResponse2 BVNEnquiry2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string AccountNumber) {
            object[] results = this.Invoke("BVNEnquiry2", new object[] {
                        AccountNumber});
            return ((BVNEnquiryResponse2)(results[0]));
        }
        
        /// <remarks/>
        public void BVNEnquiry2Async(string AccountNumber) {
            this.BVNEnquiry2Async(AccountNumber, null);
        }
        
        /// <remarks/>
        public void BVNEnquiry2Async(string AccountNumber, object userState) {
            if ((this.BVNEnquiry2OperationCompleted == null)) {
                this.BVNEnquiry2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnBVNEnquiry2OperationCompleted);
            }
            this.InvokeAsync("BVNEnquiry2", new object[] {
                        AccountNumber}, this.BVNEnquiry2OperationCompleted, userState);
        }
        
        private void OnBVNEnquiry2OperationCompleted(object arg) {
            if ((this.BVNEnquiry2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BVNEnquiry2Completed(this, new BVNEnquiry2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/ValidateBVN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ValidatorResponse ValidateBVN([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string BvnNumber) {
            object[] results = this.Invoke("ValidateBVN", new object[] {
                        BvnNumber});
            return ((ValidatorResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateBVNAsync(string BvnNumber) {
            this.ValidateBVNAsync(BvnNumber, null);
        }
        
        /// <remarks/>
        public void ValidateBVNAsync(string BvnNumber, object userState) {
            if ((this.ValidateBVNOperationCompleted == null)) {
                this.ValidateBVNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateBVNOperationCompleted);
            }
            this.InvokeAsync("ValidateBVN", new object[] {
                        BvnNumber}, this.ValidateBVNOperationCompleted, userState);
        }
        
        private void OnValidateBVNOperationCompleted(object arg) {
            if ((this.ValidateBVNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateBVNCompleted(this, new ValidateBVNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/ValidateBVNWithAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ValidatorResponse ValidateBVNWithAccount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string AccountNumber) {
            object[] results = this.Invoke("ValidateBVNWithAccount", new object[] {
                        AccountNumber});
            return ((ValidatorResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateBVNWithAccountAsync(string AccountNumber) {
            this.ValidateBVNWithAccountAsync(AccountNumber, null);
        }
        
        /// <remarks/>
        public void ValidateBVNWithAccountAsync(string AccountNumber, object userState) {
            if ((this.ValidateBVNWithAccountOperationCompleted == null)) {
                this.ValidateBVNWithAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateBVNWithAccountOperationCompleted);
            }
            this.InvokeAsync("ValidateBVNWithAccount", new object[] {
                        AccountNumber}, this.ValidateBVNWithAccountOperationCompleted, userState);
        }
        
        private void OnValidateBVNWithAccountOperationCompleted(object arg) {
            if ((this.ValidateBVNWithAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateBVNWithAccountCompleted(this, new ValidateBVNWithAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/LinkBVNWithAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LinkBVNResponse LinkBVNWithAccount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] LinkRequest Details) {
            object[] results = this.Invoke("LinkBVNWithAccount", new object[] {
                        Details});
            return ((LinkBVNResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LinkBVNWithAccountAsync(LinkRequest Details) {
            this.LinkBVNWithAccountAsync(Details, null);
        }
        
        /// <remarks/>
        public void LinkBVNWithAccountAsync(LinkRequest Details, object userState) {
            if ((this.LinkBVNWithAccountOperationCompleted == null)) {
                this.LinkBVNWithAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkBVNWithAccountOperationCompleted);
            }
            this.InvokeAsync("LinkBVNWithAccount", new object[] {
                        Details}, this.LinkBVNWithAccountOperationCompleted, userState);
        }
        
        private void OnLinkBVNWithAccountOperationCompleted(object arg) {
            if ((this.LinkBVNWithAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkBVNWithAccountCompleted(this, new LinkBVNWithAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/LinkBVNWithAccountiBPS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LinkBVNResponse LinkBVNWithAccountiBPS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] LinkRequestiBPS Details) {
            object[] results = this.Invoke("LinkBVNWithAccountiBPS", new object[] {
                        Details});
            return ((LinkBVNResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LinkBVNWithAccountiBPSAsync(LinkRequestiBPS Details) {
            this.LinkBVNWithAccountiBPSAsync(Details, null);
        }
        
        /// <remarks/>
        public void LinkBVNWithAccountiBPSAsync(LinkRequestiBPS Details, object userState) {
            if ((this.LinkBVNWithAccountiBPSOperationCompleted == null)) {
                this.LinkBVNWithAccountiBPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkBVNWithAccountiBPSOperationCompleted);
            }
            this.InvokeAsync("LinkBVNWithAccountiBPS", new object[] {
                        Details}, this.LinkBVNWithAccountiBPSOperationCompleted, userState);
        }
        
        private void OnLinkBVNWithAccountiBPSOperationCompleted(object arg) {
            if ((this.LinkBVNWithAccountiBPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkBVNWithAccountiBPSCompleted(this, new LinkBVNWithAccountiBPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/LinkBVNWithCustID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
        public LinkBVNResponse[] LinkBVNWithCustID([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] LinkRequestCustID Details) {
            object[] results = this.Invoke("LinkBVNWithCustID", new object[] {
                        Details});
            return ((LinkBVNResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void LinkBVNWithCustIDAsync(LinkRequestCustID Details) {
            this.LinkBVNWithCustIDAsync(Details, null);
        }
        
        /// <remarks/>
        public void LinkBVNWithCustIDAsync(LinkRequestCustID Details, object userState) {
            if ((this.LinkBVNWithCustIDOperationCompleted == null)) {
                this.LinkBVNWithCustIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkBVNWithCustIDOperationCompleted);
            }
            this.InvokeAsync("LinkBVNWithCustID", new object[] {
                        Details}, this.LinkBVNWithCustIDOperationCompleted, userState);
        }
        
        private void OnLinkBVNWithCustIDOperationCompleted(object arg) {
            if ((this.LinkBVNWithCustIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkBVNWithCustIDCompleted(this, new LinkBVNWithCustIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/AutoLinkBVNWithAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LinkBVNResponse AutoLinkBVNWithAccount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AutoLinkRequest Details) {
            object[] results = this.Invoke("AutoLinkBVNWithAccount", new object[] {
                        Details});
            return ((LinkBVNResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AutoLinkBVNWithAccountAsync(AutoLinkRequest Details) {
            this.AutoLinkBVNWithAccountAsync(Details, null);
        }
        
        /// <remarks/>
        public void AutoLinkBVNWithAccountAsync(AutoLinkRequest Details, object userState) {
            if ((this.AutoLinkBVNWithAccountOperationCompleted == null)) {
                this.AutoLinkBVNWithAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutoLinkBVNWithAccountOperationCompleted);
            }
            this.InvokeAsync("AutoLinkBVNWithAccount", new object[] {
                        Details}, this.AutoLinkBVNWithAccountOperationCompleted, userState);
        }
        
        private void OnAutoLinkBVNWithAccountOperationCompleted(object arg) {
            if ((this.AutoLinkBVNWithAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutoLinkBVNWithAccountCompleted(this, new AutoLinkBVNWithAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/UpdateBVN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UpdateBVNResponse UpdateBVN([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UpdateRequest Details) {
            object[] results = this.Invoke("UpdateBVN", new object[] {
                        Details});
            return ((UpdateBVNResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateBVNAsync(UpdateRequest Details) {
            this.UpdateBVNAsync(Details, null);
        }
        
        /// <remarks/>
        public void UpdateBVNAsync(UpdateRequest Details, object userState) {
            if ((this.UpdateBVNOperationCompleted == null)) {
                this.UpdateBVNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBVNOperationCompleted);
            }
            this.InvokeAsync("UpdateBVN", new object[] {
                        Details}, this.UpdateBVNOperationCompleted, userState);
        }
        
        private void OnUpdateBVNOperationCompleted(object arg) {
            if ((this.UpdateBVNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBVNCompleted(this, new UpdateBVNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class BVNEnquiryResponse {
        
        private string accountNameField;
        
        private string bVNNoField;
        
        private Response statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BVNNo {
            get {
                return this.bVNNoField;
            }
            set {
                this.bVNNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Response Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class Response {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class UpdateBVNResponse {
        
        private string bVNField;
        
        private Response responseField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BVN {
            get {
                return this.bVNField;
            }
            set {
                this.bVNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Response Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class UpdateRequest {
        
        private string bVNField;
        
        private System.DateTime dateofBirthField;
        
        private bool dateofBirthFieldSpecified;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BVN {
            get {
                return this.bVNField;
            }
            set {
                this.bVNField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateofBirth {
            get {
                return this.dateofBirthField;
            }
            set {
                this.dateofBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateofBirthSpecified {
            get {
                return this.dateofBirthFieldSpecified;
            }
            set {
                this.dateofBirthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class AutoLinkRequest {
        
        private string accountNumberField;
        
        private string bVNField;
        
        private string mobileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BVN {
            get {
                return this.bVNField;
            }
            set {
                this.bVNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class LinkRequestCustID {
        
        private string bVNField;
        
        private string cifIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BVN {
            get {
                return this.bVNField;
            }
            set {
                this.bVNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CifID {
            get {
                return this.cifIDField;
            }
            set {
                this.cifIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class LinkRequestiBPS {
        
        private string accountNumberField;
        
        private string bVNField;
        
        private string clientIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BVN {
            get {
                return this.bVNField;
            }
            set {
                this.bVNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class LinkBVNResponse {
        
        private string accountNumberField;
        
        private string cifIDField;
        
        private Response responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CifID {
            get {
                return this.cifIDField;
            }
            set {
                this.cifIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Response Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class LinkRequest {
        
        private string accountNumberField;
        
        private string bVNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BVN {
            get {
                return this.bVNField;
            }
            set {
                this.bVNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class NIBSSResponse {
        
        private string bVNField;
        
        private string dateOfBirthField;
        
        private string emailField;
        
        private string firstNameField;
        
        private string genderField;
        
        private string lastNameField;
        
        private string levelOfAccountField;
        
        private string lgaOfOriginField;
        
        private string lgaOfResidenceField;
        
        private string maritalStatusField;
        
        private string middleNameField;
        
        private string nINField;
        
        private string nameOnCardField;
        
        private string nationalityField;
        
        private string phoneNumber1Field;
        
        private string phoneNumber2Field;
        
        private string residentialAddressField;
        
        private string stateOfOriginField;
        
        private string stateOfResidenceField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BVN {
            get {
                return this.bVNField;
            }
            set {
                this.bVNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LevelOfAccount {
            get {
                return this.levelOfAccountField;
            }
            set {
                this.levelOfAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LgaOfOrigin {
            get {
                return this.lgaOfOriginField;
            }
            set {
                this.lgaOfOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LgaOfResidence {
            get {
                return this.lgaOfResidenceField;
            }
            set {
                this.lgaOfResidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NIN {
            get {
                return this.nINField;
            }
            set {
                this.nINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameOnCard {
            get {
                return this.nameOnCardField;
            }
            set {
                this.nameOnCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneNumber1 {
            get {
                return this.phoneNumber1Field;
            }
            set {
                this.phoneNumber1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneNumber2 {
            get {
                return this.phoneNumber2Field;
            }
            set {
                this.phoneNumber2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResidentialAddress {
            get {
                return this.residentialAddressField;
            }
            set {
                this.residentialAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateOfOrigin {
            get {
                return this.stateOfOriginField;
            }
            set {
                this.stateOfOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateOfResidence {
            get {
                return this.stateOfResidenceField;
            }
            set {
                this.stateOfResidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class ValidatorResponse {
        
        private NIBSSResponse resultField;
        
        private Response statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NIBSSResponse Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Response Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class BVNAccountName {
        
        private string accountNameField;
        
        private string bVNNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BVNNo {
            get {
                return this.bVNNoField;
            }
            set {
                this.bVNNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NIBBSBVNValidator")]
    public partial class BVNEnquiryResponse2 {
        
        private BVNAccountName[] bVNListField;
        
        private Response statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public BVNAccountName[] BVNList {
            get {
                return this.bVNListField;
            }
            set {
                this.bVNListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Response Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BVNEnquiryCompletedEventHandler(object sender, BVNEnquiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BVNEnquiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BVNEnquiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BVNEnquiryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BVNEnquiryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BVNEnquiry2CompletedEventHandler(object sender, BVNEnquiry2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BVNEnquiry2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BVNEnquiry2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BVNEnquiryResponse2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BVNEnquiryResponse2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateBVNCompletedEventHandler(object sender, ValidateBVNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateBVNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateBVNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidatorResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidatorResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateBVNWithAccountCompletedEventHandler(object sender, ValidateBVNWithAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateBVNWithAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateBVNWithAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidatorResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidatorResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LinkBVNWithAccountCompletedEventHandler(object sender, LinkBVNWithAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkBVNWithAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkBVNWithAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LinkBVNResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LinkBVNResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LinkBVNWithAccountiBPSCompletedEventHandler(object sender, LinkBVNWithAccountiBPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkBVNWithAccountiBPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkBVNWithAccountiBPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LinkBVNResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LinkBVNResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LinkBVNWithCustIDCompletedEventHandler(object sender, LinkBVNWithCustIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkBVNWithCustIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkBVNWithCustIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LinkBVNResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LinkBVNResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AutoLinkBVNWithAccountCompletedEventHandler(object sender, AutoLinkBVNWithAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutoLinkBVNWithAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutoLinkBVNWithAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LinkBVNResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LinkBVNResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateBVNCompletedEventHandler(object sender, UpdateBVNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateBVNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateBVNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateBVNResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateBVNResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591